// Code generated by "stringer --type=State"; DO NOT EDIT.

package puzzle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_Empty_-0]
	_ = x[Unknown-1]
	_ = x[Blocked-2]
	_ = x[Invalid-3]
	_ = x[Piece_1-4]
	_ = x[Piece_2-5]
	_ = x[Piece_3-6]
	_ = x[Piece_4-7]
	_ = x[Piece_5-8]
	_ = x[Piece_6-9]
}

const _State_name = "_Empty_UnknownBlockedInvalidPiece_1Piece_2Piece_3Piece_4Piece_5Piece_6"

var _State_index = [...]uint8{0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
