// Code generated by "stringer -type=Step"; DO NOT EDIT.

package puzzle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[North-0]
	_ = x[East-1]
	_ = x[South-2]
	_ = x[West-3]
}

const _Step_name = "NorthEastSouthWest"

var _Step_index = [...]uint8{0, 5, 9, 14, 18}

func (i Step) String() string {
	if i < 0 || i >= Step(len(_Step_index)-1) {
		return "Step(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Step_name[_Step_index[i]:_Step_index[i+1]]
}
