apiVersion: v1
kind: Namespace
metadata:
  name: pg-puzzle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-puzzle
  namespace: pg-puzzle
spec:
  selector:
    matchLabels:
      app: pg-puzzle
  replicas: 1
  template:
    metadata:
      labels:
        app: pg-puzzle
    spec:
      containers:
      - name: pg-puzzle
        image: ko://pgpuzzle
        imagePullPolicy: IfNotPresent
        args: ["server","--port=10001","--rest=8080",]
        ports:
        - containerPort: 10001
          name: grpc
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /v1/puzzle/solve-default
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: pg-puzzle
  namespace: pg-puzzle
spec:
  selector:
    app: pg-puzzle
  ports:
  - name: grpc
    port: 10001
  - name: http
    port: 8080
